### ISSUE TITLE
JWTEncoder/JWTDecoder JWT

### ISSUE THREAD

**Issue by Andrew-Lees11** [IBM-Swift/Swift-JWT#14]
You can use JSON Web tokens for information exchange. When doing this the body of the request is encoded as a JSON web token.
We would like to be able so send and retrieve JWT in the body of Codable routes.
We believe the best approach to achieve this is to create a JWTEncoder/JWTDecoder which could be used for the content type "application/jwt" to encode and decode the body between JWT and Codable types.

As part of the our JWT struct would need to be made Codable.
There is a PR for Codable JWT [here](https://github.com/IBM-Swift/Swift-JWT/pull/10)
There is a follow on PR for JWTEncoder/decoder [here](https://github.com/IBM-Swift/Swift-JWT/pull/12)

**Comment by djones6** [comment]
#12 is merged.  This will go into the next major release of Swift-JWT.
