### ISSUE TITLE
Support HS256, HS384 and HS512

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Swift-JWT#18]
BlueCryptor has these: https://github.com/IBM-Swift/BlueCryptor#hmac

**Comment by Andrew-Lees11** [comment]
Pull request adding support has been raised [here](https://github.com/IBM-Swift/Swift-JWT/pull/19)

**Comment by Andrew-Lees11** [comment]
Pull request adding support has been merged and will be tagger version 3.1
