### ISSUE TITLE
Support tvOS, macOS, watchOS

### ISSUE THREAD

**Issue by mariohahn** [IBM-Swift/Swift-JWT#33]
I am not 100% sure, but I guess it should be only a podspec update. 

I would appreciated it very much.

**Comment by mariohahn** [comment]
BlueCryptor: tvOS, watchOS missing
KituraContracts: tvOS, macOS, watchOS missing 
LoggerAPI: tvOS, macOS, watchOS missing 
BlueRSA: tvOS, watchOS missing

**Comment by mariohahn** [comment]
If I can support you in any way, let me know (:

**Comment by Andrew-Lees11** [comment]
@mariohahn 
I will look into at updating the podspec and releases. If that is all the we need to do then it shouldn't be too difficult.

**Comment by Andrew-Lees11** [comment]
I have pushed Swift-JWT version 3.2 to Cocoapods. This has tvOS, macOS and watchOS added to the podfile which should allow you to use this repo on those platforms. As such I am closing this issue.

**Comment by mariohahn** [comment]
Perfect, thanks a lot 🎉🎉
