### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by SeRG1k17** [IBM-Swift/Swift-JWT#36]
Do you plan to release a version for a Carthage?

**Comment by Andrew-Lees11** [comment]
@SeRG1k17 
Sorry but we currently have no plans to support Carthage. 
We support Cocoapods and recommend that for users on iOS.

**Comment by Andrew-Lees11** [comment]
@SeRG1k17 
I am closing this issue since we are not planning on working on it. 
If you would like to raise a PR which would add Carthage support this would be appreciated and we can reopen this.

**Comment by sushant40** [comment]
I vote we reopen this. Carthage support is fundamental to the community.
