### ISSUE TITLE
Support for PS256

### ISSUE THREAD

**Issue by markfinlabs** [IBM-Swift/Swift-JWT#55]
Hi there,

Any chance of support for PS256 on Linux? I am working with UK Open Banking which requires PS256 for message signing (*).

BR,
Mark

(*) https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1077805207/Read+Write+Data+API+Specification+-+v3.1.2#Read/WriteDataAPISpecification-v3.1.2-ProcessforSigningaPayload

**Comment by Andrew-Lees11** [comment]
Hello @markfinlabs 
I have looked into implementing this and created a pull request against [BlueRSA](https://github.com/IBM-Swift/BlueRSA/pull/46) that adds RSA-PSS signing and verifying. Once this has been approved and merged it should be fairly simple to add PS256 and PS384 support to SwiftJWT.

**Comment by markfinlabs** [comment]
Wow, that was super fast! Many thanks and much appreciated @Andrew-Lees11. I'm happy to test this on release and will report back here with my results. 

BR,
Mark

**Comment by Andrew-Lees11** [comment]
If you would like to test the PS256 support the [ps256 branch](https://github.com/IBM-Swift/Swift-JWT/tree/ps256) has .ps256 and .ps384 algorithms available.

**Comment by markfinlabs** [comment]
Thanks @Andrew-Lees11, I should be able to test this later this week, feel free to move ahead without me if that's too slow for you. : )  Appreciate your efforts.

**Comment by Andrew-Lees11** [comment]
Closing since this has now been merged and released in version 3.5.0.

**Comment by markfinlabs** [comment]
Just wanted to let you know I have been using this successfully - appreciate you adding this!

BR,
Mark
