### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "SwiftJWT":   In Podfile:     SwiftJWT

### ISSUE THREAD

**Issue by Bruce9487** [IBM-Swift/Swift-JWT#60]
Why don't I install SwiftJWT. 

<img width="894" alt="螢幕快照 2019-05-24 14 40 16" src="https://user-images.githubusercontent.com/19691907/58307708-22462e00-7e32-11e9-9f00-01c17f903e8f.png">

**Comment by ddunn2** [comment]
@Bruce9487 
Thanks for raising this issue, is it possible you could provide the contents of your Podfile? 

Thanks!

**Comment by Andrew-Lees11** [comment]
Also, What is your ios deployment target? SwiftJWT currently requires ios 11.0. If you require 10.0 you should be able to point at the 3.2 release:
```
pod 'SwiftJWT' , '~> 3.2'
```

**Comment by Bruce9487** [comment]
@ddunn2 @Andrew-Lees11  
Thanks, I change my platform to ios '11.0', and it's work to download. 
Sorry for reporting this issue.

**Comment by Andrew-Lees11** [comment]
You don't have to apologize. I'm glad we were able to help.
