### ISSUE TITLE
Missing Required Module 'OpenSSL' on Vapor.cloud and Heroku

### ISSUE THREAD

**Issue by leisurehound** [IBM-Swift/Swift-JWT#62]
Hi, I'm in the process of migrating a Swift command line app to now be a vapor app as I need to expose a couple API endpoints as well.  The command line tool successfully uses the  IBM-Swift/Swift-JWT and ideally would rather continue to use this.  I've got the vapor app running on my Mac and under Xcode successfully (and the CLI), but when I attempt to deploy and build to vapor.cloud I get the error:  

```Compile Swift Module 'App' (29 sources)
<unknown>:0: error: missing required module OpenSSL
 ```

however it does show its fetching openssl: 
```
Fetching https://github.com/IBM-Swift/OpenSSL.git
Cloning https://github.com/IBM-Swift/OpenSSL.git
Resolving https://github.com/IBM-Swift/OpenSSL.git at 1.0.3
```

Is there something else I need to include in my Package.swift for this to build on Vapor.Cloud?  Note that this same error appears on Heroku was well; I believe both are ubuntu instances.

**Comment by ianpartridge** [comment]
You'll need the appropriate `libssl-dev` for whatever Ubuntu you're on.

**Comment by leisurehound** [comment]
Thanks.  I moved onto an instance of Google Compute Engine where I have more control of what is installed, and the problem reproduces there even tho libssl-dev is installed.  So perhaps this is a Vapor OpenSSL version conflict or something.

**Comment by leisurehound** [comment]
Looks like this was an error in my Package.swift which was allowed on macOS but failed on Linux.  Documenting here for others if they come upon the same issue.

The incorrect Package.swift (which worked on macOS):

```   
targets: [
        .target(name: "App", dependencies: ["Vapor"]),
        .target(name: "Run", dependencies: ["App", "SwiftJWT"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
```

I believe the correct way to manage the dependency is:

```
    targets: [
        .target(name: "App", dependencies: ["Vapor", "SwiftJWT"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
```
