### ISSUE TITLE
error: 'SecKeyAlgorithm' is only available on watchOS 3.0 or newer

### ISSUE THREAD

**Issue by kiroskirin** [IBM-Swift/Swift-JWT#65]
I just found another issue with watchOS which there seem to be quite a lot, I will attach all the error log here as well
[carthage-xcodebuild.Mf5IJE.log](https://github.com/IBM-Swift/Swift-JWT/files/3332941/carthage-xcodebuild.Mf5IJE.log)

```swift
error: 'SecKeyAlgorithm' is only available on watchOS 3.0 or newer
public var alogrithmForEncryption: SecKeyAlgorithm {
```

**Comment by Andrew-Lees11** [comment]
Closing since this should be fixed in the 3.5.1 release
