### ISSUE TITLE
error: 'Algorithm' is only available on tvOS 10.0 or newer

### ISSUE THREAD

**Issue by kiroskirin** [IBM-Swift/Swift-JWT#66]
It seems like there are errors with tvOS as well.

```swift
error: 'Algorithm' is only available on tvOS 10.0 or newer
public func encrypted(with key: PublicKey, algorithm: Data.Algorithm) throws -> EncryptedData? {
```

Here the error log 
[carthage-xcodebuild.SVs1Np.log](https://github.com/IBM-Swift/Swift-JWT/files/3332953/carthage-xcodebuild.SVs1Np.log)

**Comment by Andrew-Lees11** [comment]
Closing since this should be fixed in the 3.5.1 release
