### ISSUE TITLE
JWTDecoder Fatal error: Index out of range

### ISSUE THREAD

**Issue by kyleishie** [IBM-Swift/Swift-JWT#73]
The JWTDecoder.decode method currently checks for the existence of headers and claims but it does so by assuming the array of strings has a count of at least 2.  Therefore, passing an empty/malformed string causes a fatal error.  I propose adding a guard to verify the array's count before attempting to access the strings.  

Is a fix for this in the works?  If not, I will submit a PR.

**Comment by redryerye** [comment]
Found this issue on my end too. Would be great if there's an update on this.

**Comment by ianpartridge** [comment]
We'd welcome a PR for this if you have time, thanks.

**Comment by kyleishie** [comment]
I totally came here to do this today.  @redryerye Thanks!

**Comment by ianpartridge** [comment]
https://github.com/IBM-Swift/Swift-JWT/releases/tag/3.6.1 - thanks all!
