### ISSUE TITLE
Make func base64urlEncodedString() public?

### ISSUE THREAD

**Issue by markfinlabs** [IBM-Swift/Swift-JWT#74]
When conforming to Claims protocol, it's quite useful to define encode(). In the default implementation of encode() (https://github.com/IBM-Swift/Swift-JWT/blob/master/Sources/SwiftJWT/Claims.swift#L78-L83), a custom Base-64 decoder is called via base64urlEncodedString() but this is not public so inaccessible for user implementations of encode().

If this custom implementation of Base-64 encoding is useful generally, should it be public so user implementations of encode can use it?

**Comment by djones6** [comment]
This seems reasonable.  I'll open a PR

**Comment by markfinlabs** [comment]
Many thanks David. I just want to say thanks to you, @Andrew-Lees11,  @ianpartridge, and the team at IBM for putting this library together because it has helped enable my own open source software which is currently being released: https://github.com/finlabsuk/open-banking-connector. It's a critical component for me! Feel free to close this issue once the pull request is in or I can come by later and do it.

**Comment by ianpartridge** [comment]
You've very welcome - it's great when we hear from happy users :)

**Comment by djones6** [comment]
@markfinlabs FYI, I made some changes to the PR (#75) based on @ianpartridge's review.

Rather than a public extension on Data, they are now static utility functions `JWTEncoder.base64urlEncodedString(data:)` and `JWTDecoder.data(base64urlEncoded:)`.

**Comment by djones6** [comment]
#75 is now tagged in `3.6.0`

**Comment by markfinlabs** [comment]
Understand the change, many thanks @djones6 for this. BR, Mark
